# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 378bf47a5b01f65b62f7c8b1b8cf21337c58b294818f1a1d803e43dd57cd49e3558e96d8436a0123d4e3bf8794149da6945a21de73a8eb450b91ed3ffc8a5ac4

test:
  secret_key_base: 5ca39492a7c61466873855695ea5e96fffec9d1e5130edb96bdf12cb11c326d411853728dbb0fad725b86a59866bfa9ed17ba43f4923db827ed54ed0f1d7fe9d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
